DATA:
  data_root: /media/agalex/WDHDD/voc2012
  train_list: /media/agalex/WDHDD/voc2012/train_aug_right.txt
  val_list: /media/agalex/WDHDD/voc2012/val.txt
  classes: 21

TRAIN:
  arch: psp
  layers: 101
  sync_bn: True  # adopt sync_bn or not
  train_h: 281
  train_w: 281
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 3  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: /media/agalex/WDHDD/voc2012/deeplabv3_101_whole_image_281/model
  weight:  # path to initial weight (default: none)
  resume:  #/media/agalex/WDHDD/voc2012/pspnet_101_new/model/train_epoch_150.pth # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: /media/agalex/WDHDD/voc2012/test_random.txt
  split: test  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 281
  test_w: 281
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: /media/agalex/WDHDD/voc2012/pspnet_101_new/model/train_epoch_150.pth # evaluation model path
  save_folder: /media/agalex/WDHDD/voc2012/pspnet101/result/test/test_random
  colors_path: /home/agalex/PycharmProjects/torch_1_3_0/segmentation/dataset/voc2012/voc2012_colors.txt # path of dataset colors
  names_path: /home/agalex/PycharmProjects/torch_1_3_0/segmentation/dataset/voc2012/voc2012_names.txt  # path of dataset category names
